name: build apk
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt install -y jq wget apktool zipalign apksigner
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run build script
        run: |
          cd ${{ github.workspace }}
          chmod +x ./build.sh
          ./build.sh
          echo "${{ secrets.KEYSTORE }}" | base64 -di > keystore.jks
          apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSPHRASE }} patched_signed.apk
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build apk
          path: ${{ github.workspace }}/patched_signed.apk
          retention-days: 5
