name: build apk
on:
  workflow_dispatch:
  schedule:
    - cron: '00 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get latest release info
        id: getLatest
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt install -y jq wget apktool zipalign apksigner
      - name: get latest mull release version
        run: |
          echo "BUILD_VERSION=$(curl -s https://divestos.org/fdroid/official/index-v1.json | jq -r '.packages."us.spotco.fennec_dos"[0].versionName')" >> $GITHUB_ENV
      - name: check if latest version was already built
        if: steps.getLatest.outputs.tag_name == ${{ env.BUILD_VERSION }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run build script
        run: |
          cd ${{ github.workspace }}
          chmod +x ./build.sh
          ./build.sh
          echo "${{ secrets.KEYSTORE }}" | base64 -di > keystore.jks
          apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSPHRASE }} patched_signed.apk
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.BUILD_VERSION }}
          files: ${{ github.workspace }}/patched_signed.apk
